<a href="https://colab.research.google.com/github/lakshmanlucky6/python_practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Declarations

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
a=np.array(10)
print(a)

10


In [ ]:
b=np.array([10,20])
b

array([10, 20])

In [ ]:
c=np.array([[1,2],[3,4],[5,6]])
c[1][1]

4

In [ ]:
d=np.array([[[[1,2],[3,4],[5,6]]],[[11,22],[33,44],[55,66]]])
d[1][1][1]

<ipython-input-15-8fa484f2517e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[[[1,2],[3,4],[5,6]]],[[11,22],[33,44],[55,66]]])


44

In [ ]:
data=[10,20,30]
print(data)
data=np.asarray(data,dtype=float)
print(data)

[10, 20, 30]
[10. 20. 30.]


In [ ]:
a=[[1,2],[3,4]]
b=np.asarray(a,dtype=float,order="C")
b
for i in np.nditer(b): print(i)

1.0
2.0
3.0
4.0


In [ ]:
a=[[1,2],[3,4]]
b=np.asarray(a,dtype=float,order="F")
b
for i in np.nditer(b): print(i)

1.0
3.0
2.0
4.0


In [ ]:
a=b"Welcome to NumPy"
np.frombuffer(a,dtype="S1",count=10,offset=1)

array([b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o', b' '],
      dtype='|S1')

In [ ]:
a=[1,2,3,4,5]
np.fromiter(a,dtype=float,count=3)

array([1., 2., 3.])

# Initializing Arrays

In [ ]:
a=np.zeros(10,dtype=int)
print(a)
b=np.zeros([2,3])
print(b)

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.full([2,3,4],10)
print(a)

[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


In [ ]:
np.random.rand(2,3)

array([[0.88164202, 0.02680942, 0.80914186],
       [0.12086548, 0.48458189, 0.30208437]])

In [ ]:
a=np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a=np.arange(10,20,2,dtype=int)
print(a)

[10 12 14 16 18]


In [ ]:
a=np.arange(1,16,1)
print(a)
a.reshape(5,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)


(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [ ]:
a=np.logspace(1,10,10,endpoint=True,base=10)
a

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])